import type { InferGetStaticPropsType, NextPage } from "next";
import { DragDropContext, Draggable, Droppable } from "react-beautiful-dnd";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
const Column = dynamic(() => import("../src/Column").then((m) => m.Column), { ssr: false });

export type Data = {
  id: number;
  name: string;
};

type Props = {
  initData: Data[];
};

export async function getStaticProps() {
  return {
    props: {
      initData: [
        {
          id: 1,
          name: "item-1",
        },
        {
          id: 2,
          name: "item-2",
        },
        {
          id: 3,
          name: "item-3",
        },
        {
          id: 4,
          name: "item-4",
        },
        {
          id: 5,
          name: "item-5",
        },
      ],
    }, // will be passed to the page component as props
  };
}

const Home: NextPage<Props> = ({
  initData,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  // const [items, setItems] = useState(initData);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Animate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DragDropContext onDragEnd={(result, provided) => {
          console.log(result);
          console.log(provided);
        }}>
         <Column initData={initData} /> 
        </DragDropContext>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
